### ISSUE TITLE
RFC: Rename project to FizzBuzzX

### ISSUE THREAD

**Issue by CMeza99** [digitalr00ts/fizzbuzz#15]
I am proposing this project be renamed to FizzBuzzX.
My reasons include:

1. Internally we already refer to this project as Fizz Buzz extreme.
2. It will help with discovery and SEO.
3. fizzbuzzx is available at PyPI
4. fizzbuzzx.com is available (though I am not opposed to other TLDs)
5. The name of the repo and the name of the package in `setup.cfg` do not match right now anyways.

@pelmini what are your thoughts?

RFC = Request For Comments

**Comment by pelmini** [comment]
Sounds reasonable. Although we could rename it to fizzbuzzexe, I like it only because of the computer joke in it. But if that doesnt seem really appealing, fizzbuzzx is good.

**Comment by CMeza99** [comment]
FizzBuzzX is gender neutral, like Latinx or folx. ;P

**Comment by pelmini** [comment]
lol, alright. Fizzbuzzx then.
