### ISSUE TITLE
Register domain for project

### ISSUE THREAD

**Issue by xsc27** [digitalr00ts/fizzbuzz#24]
We need to decide what TLD we are going to use.
* fizzbuzzx.com
* fizzbuzzx.io
* etc

I do suggest Namecheap as our registrar as, I know what features they have, they are not evil, they support DNSSEC, and we can share admin of domains.

I am assigning the ticket to @pelmini to gain experience operating a website and DNS.

**Comment by pelmini** [comment]
Registered fizzbuzzx.com!
