### ISSUE TITLE
Add Github Actions to run tests

### ISSUE THREAD

**Issue by xsc27** [digitalr00ts/fizzbuzz#7]
Implementing Continuous Integration (CI) would catch such issues as seen in issue #2.

Docs:
* [Introduction to GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions)
* [Running tests with tox](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#running-tests-with-tox)

**Comment by CMeza99** [comment]
What is CI: https://www.thoughtworks.com/continuous-integration

**Comment by CMeza99** [comment]
CI frequent utilizes server side `git` hooks. Here is an article to discuss both server and client side `git` hooks. We will use Github Actions for server side and we will go over client side (to make things like `black` run before committing).

https://www.atlassian.com/continuous-delivery/continuous-integration/git-hooks
